# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  hevysync:
    build:
      context: "C:\\Users\\Administrator\\RiderProjects\\HevyToAverage2Savage\\HevySync"
      dockerfile: "./Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net9.0/HevySync.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "hevysync:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "C:\\Users\\Administrator\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Administrator\\RiderProjects\\HevyToAverage2Savage\\HevySync:/app:rw"
    - "C:\\Users\\Administrator\\RiderProjects\\HevyToAverage2Savage:/src:rw"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\\
      2024.2.6\\Linux64:/opt/rider-debugger"
    - "C:\\Users\\Administrator\\AppData\\Local\\Programs\\Rider\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\Administrator\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_3_22_13_43_08:/var/opt/rider-debugger:rw"
    working_dir: "/app"
